FROM  eclipse-temurin:17-jre-alpine
COPY build/libs/nervecenter.jar /usr/share/app/deploy/
COPY docker/entrypoint.sh .
RUN apk upgrade --no-cache && apk add --no-cache postgresql-client bash openssl libgcc libstdc++ ncurses-libs

RUN chmod +x ./entrypoint.sh
EXPOSE 8080
ENTRYPOINT ["./entrypoint.sh"]